organizeforus/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  #Definita la route di sign_out:
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy' 
    post '/user/after_social_connection' => 'users/after_auth#create'
    get '/user/:id/:provider/unlink_account' => "users/after_auth#unlink_account", as: "unlink_account"
  end

  get '/profile' => "users#profile"


  resources :events
  resources :groups
  resources :positions

  #get 'home/index'
  root 'home#index'
  get 'home/about'
  get 'home/bho'
 
  
  resources :groups do
    resources :members , only: [:new,:edit,:create]
  end 

 resources :partecipations , only:[:new,:create,:destroy]

  resources :groups do
    resources :roles, only: [:create]
  end 
  resources :groups do
    resources :posts
  end 

  resources :posts do
    resources :comments
  end 

  resources :groups do
    resources :events
  end 

  put 'groups/:id/partecipations/edit_driver', to: 'partecipations#edit_driver', as: 'edit_driver'
  get '/groups/:group_id/partecipations', to: 'partecipations#new', as: 'new_partecipations'
  post '/groups/:group_id/partecipations', to: 'partecipations#create', as: 'partecipation_create'

  get '/groups/:id/set_created', to: 'groups#set_created', as: 'set_created'

  get '/groups/:group_id/partecipations/:role/delete_role', to: 'partecipations#delete_role', as: 'delete_role'

  get '/groups/:group_id/partecipations/show', to: 'partecipations#show', as: 'show_p'
  put '/groups/:group_id/partecipations/:member_id/update_role', to: 'partecipations#update_role', as: 'update_role'

  get '/groups/:group_id/partecipations/:member_id/update', to: 'partecipations#update', as: 'update'

  get '/groups/:group_id/partecipations/:member_id/invite', to: 'partecipations#invite', as: 'invite'


  get 'partecipations/:id/accept', to: 'partecipations#accept', as: 'accept'
  get 'partecipations/:id/decline', to: 'partecipations#decline', as: 'decline'


  get 'partecipations/:id/destroy', to: 'partecipations#destroy', as: 'destroy_partecipation'
  get 'partecipations/new_role', to: 'partecipations#new_role', as: 'new_role'
  #get '/auth/:provider/callback' => 'sessions#omniauth'

  get '/groups/:group_id/surveys/user_id/new', to: 'surveys#new', as: 'new_survey'
  post '/groups/:group_id/surveys/create', to: 'surveys#create', as: 'new_surveys'
  get '/groups/:group_id/surveys/index', to: 'surveys#index', as: 'index_survey'
  get '/groups/:group_id/surveys/:id/destroy', to: 'surveys#destroy', as: 'destroy_survey'

  get '/groups/:group_id/surveys/:survey_id/:user_id/invite', to: 'surveys#invite', as: 'invite_survey'
  post '/groups/:group_id/surveys/:survey_id/:user_id/accept', to: 'surveys#answer', as: 'answer_survey'

  get '/groups/:group_id/surveys/:survey_id/show', to: 'surveys#show', as: 'show_survey'


  get '/groups/:group_id/posts/:id/destroy' , to: 'posts#destroy', as: 'destroy_post'                                                


  put '/groups/:group_id/posts/:id/update' , to: 'posts#update', as: 'update_post'       

  post 'groups/:id/set_organization', to: 'groups#set_organization', as: 'set_organization'
                        
  get 'groups/:id/show_organization', to: 'groups#show_organization', as: 'show_organization'
  
  get 'groups/:id/:user_id/set_github_repo', to: 'groups#set_github_repo', as: 'set_github_repo'

  get 'groups/:group_id/events/:month/:day/:data_inizio/:data_fine/parameterize_date', to: 'events#parameterize_date', as: 'parameterize_date'

  

  get 'groups/:id/get_github_link', to: 'groups#get_github_link', as: 'get_github_link'

  post 'groups/:id/set_name_for_new_repository', to: 'groups#set_name_for_new_repository', as: 'set_name_for_new_repository'

  get 'groups/:id/name_repository', to: 'groups#name_repository', as: 'name_repository'

  get 'home/sign_in', to: 'home#sign_in', as: 'sign_in'

  get 'home/prova_git', to: 'home#prova_git', as: 'prova_git'

  get '/home/bho'
  get 'calendar' => 'events#event_calendar'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  match "/500", to: "errors#internal_server_error", via: :all
  match "/404", to: "errors#not_found", via: :all

  
end

organizeforus/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  def about
  end

end

organizeforus/app/helpers/home_helper.rb
module HomeHelper
end

organizeforus/app/views/home/_header.html.erb
<!--script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAmxJtTybthjWfxm6m3YCpNI7hAQbLI9Jc&libraries=places&callback=initMap" async defec data-turbolinks-eval="false"></script-->
<!--script>
    $( document ).tooltip();
</script-->
<nav class="navbar navbar-expand-lg navbar_light bg-light">
  <div class="container-fluid">

    <!--link_to tag per linkare su rails-->
    <%=link_to "#{image_tag("logo.png")}".html_safe, root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
      

<!-- Button trigger modal -->
<button type="button" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#exampleModal">
  About us
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        <h5 class="lead modal-title w-100" id="exampleModalLabel">About us</h5>
      </div>
      <div class="modal-body">
        <div style="width:20%, margin-left:90px">
        <!--lo style del div non sposta l'immagine al centro del modal-->
        <%= image_tag "profiliAboutUs.png", height: 70 %>
        </div>
        </br>
        <p class="lead">
          Hi! we're five students of Computer Engineering, and we were given the possibility to develop this web application through which you can easily manage your and your friends' events. As students, but most important as friends, we always try to find the best solution when it comes to organize a meet up. Finding a time and place that works for everyone can be hard, and that's when Organize For Us comes into play! We truly hope we can help you and make your life a little easier! Enjoy!
        </p>
      </div>
    </div>
  </div>
</div>


        <%if user_signed_in? %>
        <!-- notifiche -->

  
            <li class="nav-item"  style= "display: block">
                  <%= render "layouts/notifications" %>
            </li>

            <li class="nav-item dropdown"  style: "display: block">
                  <a class="nav-link dropdown-toggle" href="#" id="NavBarDropDown1" role="button" data-bs-toggle="dropdown" aria-expanded="false"> 
                  <%= image_tag user_avatar(current_user, 30), :size => "30x30", class: "rounded-circle" %>
                </a>

              <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="NavBarDropDown1" style="text-align: right">

              <li class="dropdown-item">
              <%=link_to "My Groups", groups_path, class:"nav-link"%>
               </li>
                <li class="dropdown-item">
                    <!--non fatto-->
                     <%=link_to "Profile", profile_path, class:"nav-link"%>
                </li>
                
                <li class="dropdown-item">
                    <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"nav-link" %> </a>
                <li>

              </ul>
            </li>

        <%else%>   
            <li class="nav-item">
                <%=link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
                <%=link_to "Login", new_user_session_path, class:"nav-link"%>
            </li>
        <%end%>
           
      </ul>
    </div>
  </div>
</nav>

organizeforus/app/views/home/about.html.erb
<h1>About us</h1>

organizeforus/app/views/home/index.html.erb
<%= stylesheet_link_tag 'homepage' %>

<div class="parallax-section">
  <div class="top-heading">
    <h1 class="display-2" style="color:white">Welcome!</h1>
  </div>
  <div class="bottom-heading">
  </div>
</div>

<div class="parallax-section">
  <div class="top-heading">
  </div>
  <div class="bottom-heading">
    <p class="lead" style="color:white">
    Wether your group is for fun or for work purposes, you can easily create it here on Organize For Us! Sign up or log in through Google, Facebook or Github, set up your profile, and start creating groups and events by simply adding the participants. You choose the amount of time necessary for the meet up, we find the best solution for you and your friends! You can also add a location for the event so the group can see it on the map, as well as surveys to quickly find out the group preferences. Have a look and find out how effortlessly it is to be organized!
    </p>
  </div>
</div>

<div class="parallax-section">
  <div class="top-heading">
  </div>
  <div class="bottom-heading">
  </div>
</div>

<pre aria-label="A cute little blob creature">༼ つ ◕_◕ ༽つ</pre>