organizeforus/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  #Definita la route di sign_out:
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy' 
    post '/user/after_social_connection' => 'users/after_auth#create'
    get '/user/:id/:provider/unlink_account' => "users/after_auth#unlink_account", as: "unlink_account"
  end

  get '/profile' => "users#profile"


  resources :events
  resources :groups
  resources :positions

  #get 'home/index'
  root 'home#index'
  get 'home/about'
  get 'home/bho'
 
  
  resources :groups do
    resources :members , only: [:new,:edit,:create]
  end 

 resources :partecipations , only:[:new,:create,:destroy]

  resources :groups do
    resources :roles, only: [:create]
  end 
  resources :groups do
    resources :posts
  end 

  resources :posts do
    resources :comments
  end 

  resources :groups do
    resources :events
  end 

  put 'groups/:id/partecipations/edit_driver', to: 'partecipations#edit_driver', as: 'edit_driver'
  get '/groups/:group_id/partecipations', to: 'partecipations#new', as: 'new_partecipations'
  post '/groups/:group_id/partecipations', to: 'partecipations#create', as: 'partecipation_create'

  get '/groups/:id/set_created', to: 'groups#set_created', as: 'set_created'

  get '/groups/:group_id/partecipations/:role/delete_role', to: 'partecipations#delete_role', as: 'delete_role'

  get '/groups/:group_id/partecipations/show', to: 'partecipations#show', as: 'show_p'
  put '/groups/:group_id/partecipations/:member_id/update_role', to: 'partecipations#update_role', as: 'update_role'

  get '/groups/:group_id/partecipations/:member_id/update', to: 'partecipations#update', as: 'update'

  get '/groups/:group_id/partecipations/:member_id/invite', to: 'partecipations#invite', as: 'invite'


  get 'partecipations/:id/accept', to: 'partecipations#accept', as: 'accept'
  get 'partecipations/:id/decline', to: 'partecipations#decline', as: 'decline'


  get 'partecipations/:id/destroy', to: 'partecipations#destroy', as: 'destroy_partecipation'
  get 'partecipations/new_role', to: 'partecipations#new_role', as: 'new_role'
  #get '/auth/:provider/callback' => 'sessions#omniauth'

  get '/groups/:group_id/surveys/user_id/new', to: 'surveys#new', as: 'new_survey'
  post '/groups/:group_id/surveys/create', to: 'surveys#create', as: 'new_surveys'
  get '/groups/:group_id/surveys/index', to: 'surveys#index', as: 'index_survey'
  get '/groups/:group_id/surveys/:id/destroy', to: 'surveys#destroy', as: 'destroy_survey'

  get '/groups/:group_id/surveys/:survey_id/:user_id/invite', to: 'surveys#invite', as: 'invite_survey'
  post '/groups/:group_id/surveys/:survey_id/:user_id/accept', to: 'surveys#answer', as: 'answer_survey'

  get '/groups/:group_id/surveys/:survey_id/show', to: 'surveys#show', as: 'show_survey'


  get '/groups/:group_id/posts/:id/destroy' , to: 'posts#destroy', as: 'destroy_post'                                                


  put '/groups/:group_id/posts/:id/update' , to: 'posts#update', as: 'update_post'       

  post 'groups/:id/set_organization', to: 'groups#set_organization', as: 'set_organization'
                        
  get 'groups/:id/show_organization', to: 'groups#show_organization', as: 'show_organization'
  
  get 'groups/:id/:user_id/set_github_repo', to: 'groups#set_github_repo', as: 'set_github_repo'

  get 'groups/:group_id/events/:month/:day/:data_inizio/:data_fine/parameterize_date', to: 'events#parameterize_date', as: 'parameterize_date'

  

  get 'groups/:id/get_github_link', to: 'groups#get_github_link', as: 'get_github_link'

  post 'groups/:id/set_name_for_new_repository', to: 'groups#set_name_for_new_repository', as: 'set_name_for_new_repository'

  get 'groups/:id/name_repository', to: 'groups#name_repository', as: 'name_repository'

  get 'home/sign_in', to: 'home#sign_in', as: 'sign_in'

  get 'home/prova_git', to: 'home#prova_git', as: 'prova_git'

  get '/home/bho'
  get 'calendar' => 'events#event_calendar'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  match "/500", to: "errors#internal_server_error", via: :all
  match "/404", to: "errors#not_found", via: :all

  
end

organizeforus/app/models/partecipation.rb
class Partecipation < ApplicationRecord
    belongs_to :user
    belongs_to :group

    before_destroy :cleanup_notification
    @list_role = Array.new

    scope :list_member, ->(group){
        arr=Array.new
        where(group_id: group).each do |member| 
          arr << User.find(member.user_id).email
        end
        return arr
    }

    scope :member, -> { where(:accepted => true) }

    validates :role, presence: true
    validates :user_id, presence: true

    def partecipations_number_for_survey(time,group)
      group.partecipations.where('created_at < ?', time).count
    end

    
  
    

  private 

  def cleanup_notification
    User.find(self.user_id).notifications.destroy_all
  end

    




end

organizeforus/app/controllers/partecipations_controller.rb
class PartecipationsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_authorized? , only: [:new, :create]
  before_action :correct_user?, only: [:new,:create,:show,:update]
  before_action :check_admin, only: [:show]
  
  def index
  end

  def new
    @partecipation=Partecipation.new
    @partecipations=Partecipation.all
    @group=Group.find(params[:group_id])
    if @group.fun
      if @group.created?
        render "member_fun"
      else
        render "new_fun"
      end
    else
      if @group.created?
        render "member_work"
      else
        render "new_work"
      end
  end
end

  def create
    @user=partecipation_params[:user_id]
    @id=User.find_by(email: @user)
    @group=partecipation_params[:group_id]
    @g=Group.find(@group)
    @color= partecipation_params[:role_color]
    @role= partecipation_params[:role]
    if @role == "" || @role == " " || @role== nil
      @role="No Role"
    end

   
    session[:return_to] ||= request.referer 

    if @id!=nil # se esiste questo utente
      if Partecipation.where(group_id: @group).where(user_id: @id.id).empty? #se non è già membro
        if @g.created=="t" 
          notify_recipent(@g,@id,@role) 
        end #invia notifica per accettare o meno l'invito al gruppo
        
        if @g.work==true
          @partecipation=Partecipation.new(group_id: @group, user_id: @id.id, role: @role, role_color: @color, admin: false)
          respond_to do |format|
            if @partecipation.save
              format.html { redirect_to session.delete(:return_to), notice: 'Member was succesfully added' }
              format.json { render :@part.json }
            else
              format.html { render html: "Something gone wrong"+ @partecipation.errors}
              format.json { render json: @partecipation.errors, status: :unprocessable_entity }
            end
          end

        else #fun group
          
          if @role=='1' #E DD
            @g.delect_driver
            @partecipation=Partecipation.new(group_id: @group, user_id: @id.id, role: 'Driver', admin: false)
            respond_to do |format|
              if @partecipation.save
                format.html { redirect_to session.delete(:return_to), notice: 'Member was succesfully added' }
                format.json { render :@part.json }
              else
                format.html { render html: "Something gone wrong"+ @partecipation.errors}
                format.json { render json: @partecipation.errors, status: :unprocessable_entity }
              end
            end

          else # non è DD
            @partecipation=Partecipation.new(group_id: @group, user_id: @id.id, role: 'No Role',admin: false)
            respond_to do |format|
              if @partecipation.save
                format.html { redirect_to session.delete(:return_to), notice: 'Member was succesfully added'  }
                format.json { render :@part.json }
              else
                format.html { render html: "Something gone wrong"+ @partecipation.errors}
                format.json { render json: @partecipation.errors, status: :unprocessable_entity }
              end
            end
          end 

        end 

      else
        respond_to do |format|
            format.html { redirect_to session.delete(:return_to), notice: 'Member was already subscribe' }
            format.json { render :@part.json }
        end
      end 

    else 
      if @user!=nil && @user!=" "
        GroupMailer.with(group: @g,user: @user, creator: current_user).join_comunity.deliver_later
      end
      respond_to do |format|
        format.html { redirect_to session.delete(:return_to), notice: 'Sent invite' }
        format.json { render :@part.json }
       end       
    end 

  end

  def show
    @group=Group.find(params[:group_id])
    if @group.fun
        render "show_fun"
    else
        render "show_work"
    end

  end

  def destroy
    @partecipation=Partecipation.find(params[:id])
    @partecipation.destroy

    respond_to do |format|
      session[:return_to] ||= request.referer 

      format.html { redirect_to session.delete(:return_to), notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def edit_driver
    @group=Group.find(params[:id])
    @user_id=User.find_by(email: drive_params[:role])
    if @group.has_designeted_driver?
      @group.delect_driver
      Partecipation.where(group_id: @group.id, user_id:@user_id.id).update(role: "Driver")
      respond_to do |format|
        session[:return_to] ||= request.referer 
        format.html { redirect_to session.delete(:return_to), notice: "Designated Driver was modified." }
        format.json { head :no_content }
      end
    else
      Partecipation.where(group_id: @group.id, user_id:@user_id.id).update(role: "Driver")
      respond_to do |format|
        session[:return_to] ||= request.referer 
        format.html { redirect_to session.delete(:return_to), notice: "Designated Driver added." }
        format.json { head :no_content }
      end
    end
  end

  def delete_role
    @group=Group.find(params[:group_id])
    @role=params[:role]
    Partecipation.where(role: @role).update(role: "No Role")
    respond_to do |format|
      session[:return_to] ||= request.referer 
      format.html { redirect_to session.delete(:return_to), notice: "Role: "+@role+" was deleted, the member who had that role now are general member, please update their position if you need " }
      format.json { head :no_content }
    end
  end

  def update_role
    @group=Group.find(params[:group_id])
    @member=User.find(params[:member_id])
    @color=params[:role_color]
    @role=params[:role]
    @admin=params[:admin]
    @part=Partecipation.find_by(group_id: @group.id, user_id: @member.id)
    if @role != nil && @role != ""
      if @role==@part.role && ( @part.admin==true && @admin=="0")
        @part.update(role: "No Role", role_color: @color, admin: @admin)
      else
       @part.update(role: params[:role], role_color: @color, admin: @admin)
       respond_to do |format|
        format.html { redirect_to show_p_url(@group), notice: "Role updated" }
        format.json { head :no_content }
        
       end
      end
    else
      respond_to do |format|
        format.html { redirect_to show_p_url(@group), notice: "Empty role" }
        format.json { head :no_content }
      end
    end

  end

  def update
    @group=Group.find(params[:group_id])
    @member=User.find(params[:member_id])
    render "update_role"
  end


  def invite 
    @group=Group.find(params[:group_id])
    @user=User.find(params[:member_id])
    @partecipation= Partecipation.where(group_id: @group.id, user_id: @user.id).take
    mark_notification_as_read
  end

  def accept
    @partecipation=Partecipation.find(params[:id])
    @partecipation.update(accepted: true)
    @group=Group.find(@partecipation.group_id)
    flash.alert="Accept"
    respond_to do |format|
      format.html { redirect_to group_url(@group), notice: "Accepted" }
      format.json { head :no_content }
    end

  end

  def decline
    @partecipation=Partecipation.find(params[:id])
    @partecipation.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Declined" }
      format.json { head :no_content }
    end
  end

  def getRole(user,group)
    Partecipation.where(group_id: group.id, user_id: User.where(email: user.email).take.id ).take.role
  end

=begin
  def correct_user 
    if current_user==
      true
    end
  end
=end

def is_authorized? 
   @group=Group.find(params[:group_id])
   if @group.user != current_user
    if !Partecipation.find_by(group_id:@group, user_id: current_user).nil?
      if Partecipation.find_by(group_id:@group, user_id: current_user).admin == false
        redirect_to group_url(@group), notice: "Not Authorized to create Partecipation on this Group"
      end
    else 
      redirect_to group_url(@group), notice: "Not Authorized to create Partecipation on this Group"
    end
   end
end

def correct_user? 
  @group=Group.find(params[:group_id])
  if @group.user != current_user
   if Partecipation.find_by(group_id:@group, user_id: current_user).nil?
       redirect_to root_path, notice: "Not Authorized on this Group"
   end
  end
end

def check_admin
  @group=Group.find(params[:group_id])
  @group.partecipations.each do |p|
    if p.admin==true
      p.update!(role: "Admin")
    end
  end
end




private

  def partecipation_params
    params.require(:partecipation).permit(:user_id,:group_id,:role,:role_color, :admin)
  end

  def role_params
    params.require(:partecipation).permit(:role)
  end

  def drive_params
    params.require(:partecipation).permit(:role)
  end

  def mark_notification_as_read
    @group=Group.find(params[:group_id])
    if current_user
      notifications_to_mark_as_read= @group.notifications_as_group.where(recipient: current_user)
      notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
    end
  end

  def notify_recipent(group,user,role)
    g=GroupNotification.with(group: group, user: user, creator: group.user,role: role).deliver_later(user) # creazione notifiche
  end




end

organizeforus/app/helpers/partecipations_helper.rb
module PartecipationsHelper
end

organizeforus/app/views/partecipations/_form.html.erb
<%if !user_signed_in? %>
  <% controller.redirect_to new_user_session_path %>
<%end%>

<%= form_with  url: partecipation_create_path(@group), model: @partecipation do |form| %>
    
    <div class="field form group">
      </br>
      <div class="row"> 
          <div class="col-6">
            <% form.label :user_id, style: "display: block" %>
            <%= form.text_field :user_id,id:"EmailUser", class:"form-control", placeholder:"Enter user email" %>
          </div>

          <script type="text/javascript">
              function color_check(){
                var list=document.getElementById("role_list").value;
                var color_box=document.getElementById("color_box");
                var nodes=document.getElementById("item").childNodes;
                var res=null;

                for(var i=0; i<nodes.length; i++){
                  if (list==nodes[i].text) {
                    if(list=="Please choose a role"){
                      document.getElementById("role_list").value="";
                    }
                  else res=nodes[i]; 
                  }
                }

              if(res!=null){ 
                var color=res.getAttribute('data-value');
                if ( color != 0 ) {
                  color_box.value=color;
                }
              } 
            else{
                color_box.disabled = false; 
                color_box.value="#000000";
                return;
              }
            }

          </script>

          <% if @group.work==true %>
            <div class="col-4"> 
              <% form.label :role, style: "display: block" %>
              <%= form.text_field :role, value:"",id:"role_list", oninput: "color_check()", class:"form-control", list:'item', placeholder:"Enter Role" %>
              <datalist id='item'> 
                <% Group.role_list(@group).each do |r| %>
                  <option data-value="0">Please choose a role</option>
                  <option data-value= "<%=@group.getColor(@group.id,r)%>" ><%=r%></option>
                <%end %>
              </datalist>      
            </div>

            <div class="col">
              <% form.label :role_color, style: "display: block" %> 
              <%= form.color_field :role_color, id:"color_box", class:"form-control, btn-sm, rounded-6", style:"rounded" %>
            </div>
          </div>

          


          <%else %>
            <div class="col">
              <% form.label :role, class:"form-check-label" %> 
              <%= form.check_box :role, value:"0", class:"form-check-input" %> Designated Driver
            </div>
        </div>
          <%end%>

          <% if @group.id==nil %>
          <% value =Group.last.id+1%>
          <% else %>
          <% value=@group.id %> 
          <% end %>
          <% form.label :group_id, style: "display: block" %>
          <%= form.text_field :group_id, class:"form-control",value: value, type: "hidden" %>
        </div>
        <div>
          </br>
          <%= form.submit class:"btn btn btn-sm border border-dark"%>
        </div>
    <% end %>
      

organizeforus/app/views/partecipations/invite.html.erb
<html>
<head>
    <%if !user_signed_in? %>
        <% controller.redirect_to new_user_session_path %>
    <%end%>
</head>
<body>

    <div class="container-sm ;align-middle" style="text-align:center; heigth:50% ;width:50%; margin-top:10%">
        <div class="row align-item-center">

        <span>Hi <b><%=@user.name%> <%=@user.surname%></b>, we want to inform you that <b> <%=@group.user.name%> <%=@group.user.surname%></b> invited you to join <br><b> <%=@group.name%> </b>group! <br> 
        Into <%=@role %>
        if you want to accept the invitation, please click yes below. <br>
        </span>
        </div>
        <br>
        <div class="row align-item-center">
            <div class="col"> </div>
            <div class="col"> </div>
            <div class="col">
                <%=link_to  "Yes", accept_path(@partecipation.id), class:"btn btn-primary" %>         
            </div>
            <div class="col">
                <%= link_to  "No", decline_path(@partecipation.id),class:"btn btn-primary"  %>         
            </div>
            <div class="col"> </div>
            <div class="col"> </div>

        </div> 
    </div>


</body>
</html>

organizeforus/app/views/partecipations/member_fun.html.erb
<%if !user_signed_in? %>
  <% controller.redirect_to new_user_session_path %>
<%end%>

<!-- AGGIUNTA MEMNBRI PER QUANDO IL GRUPPO è GIA STATO CREATO-->
 <div class="row" style="width:100%">
      <div class="col" > 
      <h1 class="display-6">Add a new member to the group</h1>
      </div>     
      <div class="col" > <div class="row" style=" text-align:right">
        <div class="col">
        </div>
        
        <div class="col">
        </div>
        <div class="col">
          <a href="<%= group_path(@group) %>" style="color: black" title="Back">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-90deg-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1.146 4.854a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 4H12.5A2.5 2.5 0 0 1 15 6.5v8a.5.5 0 0 1-1 0v-8A1.5 1.5 0 0 0 12.5 5H2.707l3.147 3.146a.5.5 0 1 1-.708.708l-4-4z"/>
            </svg>
          </a>
        </div>
         </div>
      </div>
  </div>
<br>
<%= render "partecipations/form"%>
<br>
<% Group.list_members(@group).each do |part| %>
    <div class="row">
    <div class="col-3" >
    
    <li style='list-style-type: circle'> <%= User.find(part.user_id).email %> </div>
    
    <div class="col"> 
    <%= part.role %></li>
</div>
<div class="col mb-1"> 
<%= link_to "Delete", [:destroy, part] , class:"btn btn-danger", data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
} %>  </div>

</li> 
</div>
  <% end %>
<br>
</div>

organizeforus/app/views/partecipations/show_work.html.erb
<div class="row" style="width:100% ;text-align:right">
  <div class="col" style="width:80%"> 
  </div>  

  <div class="col" > 
    <div class="row" style=" text-align:right">
      <div class="col" >
      <a href="<%= group_url(@group) %>" title="Back" style="color: black">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-90deg-left" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M1.146 4.854a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 4H12.5A2.5 2.5 0 0 1 15 6.5v8a.5.5 0 0 1-1 0v-8A1.5 1.5 0 0 0 12.5 5H2.707l3.147 3.146a.5.5 0 1 1-.708.708l-4-4z"/>
      </svg>
      </a>
      </div>
      <% if current_user==@group.administrator %> 
      <div class="col" >
      <a href="<%= new_partecipations_url(@group) %>" title="Add member" style="color: black">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
      <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
      <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
      </svg>
      </a>
      </div>
      <% end %>
    </div>
  </div>
  
</div>


<html>
<head> <% content_for :head do %>
  <%= javascript_import_module_tag "reload" %>
<% end %>

<%if !user_signed_in? %>
  <% controller.redirect_to new_user_session_path %>
<%end%> </head>
<body>
<h1 class="display-6">Members List</h1>


<br>
<!-- QUESTA PAGINA è MOSTRARE I MEMBRI DI UN GRUPPO TIPO WORK -->

<div class="row">
<div class="col-3"> Email </div>
<div class="col-3"> Role </div>
<div class="col"> Status </div>
<div class="col">  </div>
<div class="col">  </div>
<hr class="my"> </hr>
<br>
</div>

<% @group.partecipations.each do |member| %>
  <%= stylesheet_link_tag "application" %> 

<div class="row"> 

  <div class="col-3">
    <li style="list-style-type: circle ; color: <%=member.role_color%>" >  
        <span> <%= member.user.email %> </span> 
    </li> 
  </div>
  <div class="col-3" id="col_role"> 
    <%=member.role%> 
  </div>

<div class="col">
<% if @group.accepted?(member.user.id)%>
 Member
<%else %>
 Pending
<% end %>
</div>

<%if @group.user==current_user && member.user.email!= @group.user.email%>
  <div class="col mb-1"> 
     <%= link_to "Delete", [:destroy, member] ,class:"btn btn-danger btn-sm", data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %> 
  </div>

  <div class="col">
    <%= link_to "Update role", update_url(@group,member.user.id), class:"btn btn btn-sm border border-dark" %>
  </div>
        
  </div>
<%else %>

<div class="col mb-2"> </div>
  <div class="col"> </div>   
  </div>
<% end %>

<% end %><br><br>
<!-- Righe per indietro o aggiunta 
    <div class="row">
      <div class="col-1" ,style="text-align: right">
      <%= link_to "Back", @group, class:"btn btn-secondary" %>
      </div>
      <div class="col">
      <%= link_to "New Member", new_partecipations_url(@group), class:"btn btn-secondary" %>
      </div>
    </div></body>
    -->
</html>

organizeforus/app/views/partecipations/update_role.html.erb
<!-- PAGINA DOVE MODIFICARE IL RUOLO DI UN PARTECIPANTE-->

<html>
<head>
  <%if !user_signed_in? %>
    <% controller.redirect_to new_user_session_path %>
  <%end%></head>
<body>

<div class="row" style=" text-align:right">
  <a href="<%= group_url(@group) %>" title="Back" style="color: black">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-90deg-left" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M1.146 4.854a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 4H12.5A2.5 2.5 0 0 1 15 6.5v8a.5.5 0 0 1-1 0v-8A1.5 1.5 0 0 0 12.5 5H2.707l3.147 3.146a.5.5 0 1 1-.708.708l-4-4z"/>
    </svg>
  </a>
</div>
<br>

<h1 class="display-6">Members List</h1>



<% @group.partecipations.each do |member| %>
<!-- non mi riconosce uguali i due id perche uno è della partecipazione lascio cosi che tanto la mail è univoca-->
<% if member.user.email!=@group.user.email%>
<%if member.user.email==@member.email%>
<div class="row"> 
    <div class="col">
      <li style='list-style-type: circle'> <%= member.user.email %> </li> 
    </div>


    <script type="text/javascript">
          function color_check(){
            var list=document.getElementById("role_list").value;
            var color_box=document.getElementById("color_box");
            var nodes=document.getElementById("item").childNodes;
            var res=null;

            for(var i=0; i<nodes.length; i++){
              if (list==nodes[i].text) {
                if(list=="Please choose a role"){
                  document.getElementById("role_list").value="";
                }
              else res=nodes[i]; 
              }
            }

          if(res!=null){ 
            var color=res.getAttribute('data-value');
            if ( color != 0 ) {
              color_box.value=color;
            }
          } 
        else{
            color_box.disabled = false; 
            color_box.value="#000000";
            return;
          }
        }

      </script>

    <div class="col">
        <%= form_with url: update_role_url, model: @partecipations, method: :put do |form| %>
            <% form.label :role, style: "display: block" %>
            <%= form.text_field :role, class:"form-control", list:'item',value: member.role %>
                <datalist id='item'>
            <% Group.role_list(@group).each do |r| %>
                <option data-value="0">Please choose a role</option>
                <option data-value= "<%=@group.getColor(@group.id,r)%>" ><%=r%></option>
                <%end %>
                </datalist>      </div>

                <div class="col-1">
                <% form.label :role_color, style: "display: block" %> 
                <%= form.color_field :role_color, id:"color_box", class:"form-control, btn-sm, rounded-6", style:"rounded" %>
                </div>

                <div class="col-2">
                <% form.label :admin, style: "display: block" %> Make admin:
                <%= form.check_box :admin, class:"form-control,rounded-6", checked: member.admin %>
                </div>
          

        <div class="col">
            <%= form.submit class:'btn btn-secondary btn-sm;'%>
    </div>
    <%end%>
    <br>

<% else %>



<div class="row"> <div class="col">
<li style='list-style-type: circle'> <%= member.user.email %> </li> </div>

<div class="col" id="col_role"> Role: <%=member.role%> </div>


<%if @group.user==current_user %>
<div class="col">  <%= link_to "Delete", [:destroy, member] ,class:"btn btn-danger btn-sm", data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              } %> 
              </div>
<div class="col">

<%= link_to "Update" ,update_role_path(@group,member) %>
</div>
       
</div>
<% end %>

<% end %><br><br>
<%end%>
<%end%>

</body>
</html>