organizeforus/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  #Definita la route di sign_out:
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy' 
    post '/user/after_social_connection' => 'users/after_auth#create'
    get '/user/:id/:provider/unlink_account' => "users/after_auth#unlink_account", as: "unlink_account"
  end

  get '/profile' => "users#profile"


  resources :events
  resources :groups
  resources :positions

  #get 'home/index'
  root 'home#index'
  get 'home/about'
  get 'home/bho'
 
  
  resources :groups do
    resources :members , only: [:new,:edit,:create]
  end 

 resources :partecipations , only:[:new,:create,:destroy]

  resources :groups do
    resources :roles, only: [:create]
  end 
  resources :groups do
    resources :posts
  end 

  resources :posts do
    resources :comments
  end 

  resources :groups do
    resources :events
  end 

  put 'groups/:id/partecipations/edit_driver', to: 'partecipations#edit_driver', as: 'edit_driver'
  get '/groups/:group_id/partecipations', to: 'partecipations#new', as: 'new_partecipations'
  post '/groups/:group_id/partecipations', to: 'partecipations#create', as: 'partecipation_create'

  get '/groups/:id/set_created', to: 'groups#set_created', as: 'set_created'

  get '/groups/:group_id/partecipations/:role/delete_role', to: 'partecipations#delete_role', as: 'delete_role'

  get '/groups/:group_id/partecipations/show', to: 'partecipations#show', as: 'show_p'
  put '/groups/:group_id/partecipations/:member_id/update_role', to: 'partecipations#update_role', as: 'update_role'

  get '/groups/:group_id/partecipations/:member_id/update', to: 'partecipations#update', as: 'update'

  get '/groups/:group_id/partecipations/:member_id/invite', to: 'partecipations#invite', as: 'invite'


  get 'partecipations/:id/accept', to: 'partecipations#accept', as: 'accept'
  get 'partecipations/:id/decline', to: 'partecipations#decline', as: 'decline'


  get 'partecipations/:id/destroy', to: 'partecipations#destroy', as: 'destroy_partecipation'
  get 'partecipations/new_role', to: 'partecipations#new_role', as: 'new_role'
  #get '/auth/:provider/callback' => 'sessions#omniauth'

  get '/groups/:group_id/surveys/user_id/new', to: 'surveys#new', as: 'new_survey'
  post '/groups/:group_id/surveys/create', to: 'surveys#create', as: 'new_surveys'
  get '/groups/:group_id/surveys/index', to: 'surveys#index', as: 'index_survey'
  get '/groups/:group_id/surveys/:id/destroy', to: 'surveys#destroy', as: 'destroy_survey'

  get '/groups/:group_id/surveys/:survey_id/:user_id/invite', to: 'surveys#invite', as: 'invite_survey'
  post '/groups/:group_id/surveys/:survey_id/:user_id/accept', to: 'surveys#answer', as: 'answer_survey'

  get '/groups/:group_id/surveys/:survey_id/show', to: 'surveys#show', as: 'show_survey'


  get '/groups/:group_id/posts/:id/destroy' , to: 'posts#destroy', as: 'destroy_post'                                                


  put '/groups/:group_id/posts/:id/update' , to: 'posts#update', as: 'update_post'       

  post 'groups/:id/set_organization', to: 'groups#set_organization', as: 'set_organization'
                        
  get 'groups/:id/show_organization', to: 'groups#show_organization', as: 'show_organization'
  
  get 'groups/:id/:user_id/set_github_repo', to: 'groups#set_github_repo', as: 'set_github_repo'

  get 'groups/:group_id/events/:month/:day/:data_inizio/:data_fine/parameterize_date', to: 'events#parameterize_date', as: 'parameterize_date'

  

  get 'groups/:id/get_github_link', to: 'groups#get_github_link', as: 'get_github_link'

  post 'groups/:id/set_name_for_new_repository', to: 'groups#set_name_for_new_repository', as: 'set_name_for_new_repository'

  get 'groups/:id/name_repository', to: 'groups#name_repository', as: 'name_repository'

  get 'home/sign_in', to: 'home#sign_in', as: 'sign_in'

  get 'home/prova_git', to: 'home#prova_git', as: 'prova_git'

  get '/home/bho'
  get 'calendar' => 'events#event_calendar'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  match "/500", to: "errors#internal_server_error", via: :all
  match "/404", to: "errors#not_found", via: :all

  
end

organizeforus/app/models/event.rb
class Event < ApplicationRecord
  belongs_to :group
  belongs_to :user
  
  has_one :position, dependent: :destroy
  accepts_nested_attributes_for :position, allow_destroy: true

  #h_g=self.group.houres
  has_many :notifications, as: :recipient, dependent: :destroy
  has_noticed_notifications model_name: 'Notification'

  validates :title, presence: true
  validates :description, presence: true
  validates :mode, presence: true
  validates :type_of_hours, presence: true 

  validates :end_date, presence: true,comparison: { greater_than_or_equal_to: :start_date}
  validates :start_date, presence: true


  #validates :houres, numericality: { greater_than: 0 }
  #validates :houres, numericality: {less_than: h_g}, if: :houre_on_group

  def readonly?
    false
  end
  
  def get_array_members
    members=self.members.remove("[").remove("]").remove('"').remove(' ').split(',')
    array=Array.new
    members.each do |memb|
      array<<User.find_by(email: memb)
    end
    return array
  end

  def email_guest_list
    members=self.members.remove("[").remove("]").remove('"').remove(' ').split(',')
    return members
  end

end

organizeforus/app/controllers/events_controller.rb
require "google/apis/calendar_v3"
require "google/api_client/client_secrets.rb"
class EventsController < ApplicationController
before_action :authenticate_user!
before_action :is_authorized? , only: [:destroy]
before_action :is_authenticate?, only: [:new]
before_action :is_ok?, except: [:create]
before_action :is_a_member?, only:[:show]
before_action :correct_user, only: [:new, :create]

  include Search

 CALENDAR_ID = 'primary'
    def index
      @group=Group.find(params[:group_id])
      @events=@group.events
        #@event_list =  get_all_events(current_user)
        #@events = current_user.events
        #@try = organize_for_us(Event.first.group , '2022-08-25' , '2022-08-26' , '08:00:00' , '17:00:00' , 1)
        # <% @event_list.items.each do |event|%>
         # <li><%= event.summary%> </li>
          #<%end %>
      

        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        # parametri dell'altra versione dell'algoritmo
        # @event_list =  get_all_events_in_range(current_user, DateTime.strptime("28/08/2022 23:59:00 +0200", "%d/%m/%Y %H:%M:%S %Z").rfc3339, DateTime.strptime("25/08/2022 00:00:00 +0200", "%d/%m/%Y %H:%M:%S %Z").rfc3339)
        # @events = current_user.events
        # @try = organize_for_us(Event.first.group , '2022-08-25' , '2022-08-28' , '08:00:00' , '17:00:00' , 1)
        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    end
    def event_calendar; end

    def new
      @group=Group.find(params[:group_id])
      @event=Event.new
      d=DateTime.now
      @dataI= d
      @dataF= DateTime.new(d.year,d.month,d.day,d.hour+1,d.second)
    end

    def create
      #authorize! :create, @event, :message => "BEWARE: you are not authorized to create new events."
      @event = Event.new(event_params)
      @group=Group.find(event_params[:group_id])
      client = get_google_calendar_client current_user
      eevent = params[:event]
      event = get_event eevent
      if @event.mode == "Online"
        ret=client.insert_event('primary', event, conference_data_version: 1)
        @event.update(meet_uri: ret.conference_data.entry_points.first.uri ) 
      else
        client.insert_event('primary', event)
      end
      flash[:notice] = 'Event was successfully added.'
      respond_to do |format|
        if @event.save!
          if position_params[:street]!="" && position_params[:city]!="" && position_params[:province]!="" && position_params[:country]!=""
            @position= Position.new(position_params)
            @position.event_id=@event.id
            @position.save
          end
          @event.get_array_members.each do |member|
            notify_recipent(@group,@event,member)
          end
          format.html { redirect_to group_event_path(@group,@event), notice: "Event was successfully created." }
          format.json { render :show, status: :ok, location: @event }
        else
          format.html { redirect_to  groups_path, notice: "Event was not successfully updated."}
          format.json { render :index , status: :unprocessable_entity }
        end
      end   
    end

    def is_authorized
      @group=Group.find(params[:group_id])
      if @group.list_accepted.where(user_id: current_user.id).empty?
        redirect_to root_path, notice: "Not Authorized on this Group"
      end
    end


    def show
        @group=Group.find(params[:group_id])
        @event=Event.find(params[:id])
        mark_notification_as_read
        @location= @event.position
    end

    def get_event event
      
        attendees = event[:members].map{ |t| {email: t.strip} }        
        eevent = Google::Apis::CalendarV3::Event.new(
          summary: event[:title],
          location: '800 Howard St., San Francisco, CA 94103',
          description: event[:description],
          start: {
            date_time: Time.new(event['start_date(1i)'],event['start_date(2i)'],event['start_date(3i)'],event['start_date(4i)'],event['start_date(5i)']).to_datetime.rfc3339,
            time_zone: "Europe/Rome"
          },
          end: {
            date_time: Time.new(event['end_date(1i)'],event['end_date(2i)'],event['end_date(3i)'],event['end_date(4i)'],event['end_date(5i)']).to_datetime.rfc3339,
            time_zone: "Europe/Rome"
          },
          conference_data: Google::Apis::CalendarV3::ConferenceData.new(
            create_request: Google::Apis::CalendarV3::CreateConferenceRequest.new(
              request_id: "sample123",
              conference_solution_key: Google::Apis::CalendarV3::ConferenceSolutionKey.new(
                type: "hangoutsMeet"
              )
            )
          ),
          attendees: attendees,
          reminders: {
            use_default: false,
            overrides: [
              Google::Apis::CalendarV3::EventReminder.new(reminder_method:"popup", minutes: 10),
              Google::Apis::CalendarV3::EventReminder.new(reminder_method:"email", minutes: 20)
            ]
          },
          notification_settings: {
            notifications: [
                            {type: 'event_creation', method: 'email'},
                            {type: 'event_change', method: 'email'},
                            {type: 'event_cancellation', method: 'email'},
                            {type: 'event_response', method: 'email'}
                           ]
          }, 'primary': true
        )
      end

      def destroy
        @event=Event.find(params[:id])
        @group=Group.find(params[:group_id])
        respond_to do |format|
        if @event.destroy
            format.html { redirect_to group_url(@group), notice: "Event succesfully destroy." }
            format.json { render :show, status: :ok, location: @group }
        else
            format.html { redirect_to root_path, notice: "Event was not successfully destroy."}
            format.json { render :edit , status: :unprocessable_entity }
        end
      end
        
      end

      def is_authorized?
        @group=Group.find(params[:group_id])
        @event=Event.find(params[:id])
        if @event.user_id != current_user.id
          redirect_to root_path, notice: "Not Authorized on this Event "
        end
      end

      def is_a_member?
        @event=Event.find(params[:id])
        members=@event.get_array_members
        if !members.include?(current_user) && @event.user != current_user

          redirect_to group_url(Group.find(params[:group_id])), notice: "Not Authorized on this Event"
        end

      end


      def is_authenticate?
        if !User.last.access_token?
          redirect_to group_url(Group.find(params[:group_id])), notice: "Not Authenticate"
        end
      end

       def is_ok?
     
        @group=Group.find(params[:group_id])
         if @group.list_accepted.where(user_id: current_user.id).empty?
           redirect_to root_path, notice: "Not Authorized ok"
         end
        end

        def parameterize_date
          @event=Event.new
          d=params[:day].to_i
          m=params[:month].to_i
          oraI=params[:data_inizio].to_datetime
          oraF=params[:data_fine].to_datetime
          @dataI= DateTime.new(DateTime.now.year,m,d,oraI.hour,oraI.minute,oraI.sec)
          @dataF= DateTime.new(DateTime.now.year,m,d,oraF.hour,oraF.minute,oraF.sec)
          render "new"
        end

        def correct_user
          @group = current_user.groups.find_by(id: params[:group_id])
            if @group.nil? 
              if !Partecipation.find_by(group_id: params[:id], user_id: current_user.id).nil?
                if Partecipation.find_by(group_id: params[:id], user_id: current_user.id).admin == false
                  redirect_to group_url(Group.find(params[:id])), notice: "Not Authorized to Edit this Group"
                end
              else 
                redirect_to group_url(Group.find(params[:id])), notice: "Not Authorized to Edit this Group"
              end
            end
        end



    private
    def event_params
      params.require(:event).permit(:title, :description, :user_id, :mode, :type_of_hours, :group_id,:start_date, :end_date, members: [])

    end

    def position_params
      params.require(:position).permit!
    end

    def notify_recipent(group,event,user)
      EventNotification.with(user: user,event: event, group: group).deliver_later(user)
    end

    def mark_notification_as_read
      @event=Event.find(params[:id])
      if current_user
        notifications_to_mark_as_read= @event.notifications_as_event.where(recipient: current_user)
        notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
      end
    end

end

organizeforus/app/helpers/events_helper.rb
module EventsHelper
end

organizeforus/app/views/events/_form.html.erb
<%= form_with  url: group_events_path, method: :post , model: @event do |form| %>
    <div class="row ; mb-2">
    <div class="row">
            <div class="col mb-2">
                <% form.label :name, style: "display: block" %> Name: <br>
                <%= form.text_field :name, size: "30x3" %>
            </div>
        <div class="col mb-2">
            <% form.label :description, style: "display: block" %> Description: <br>
            <%= form.text_area :description, size: "30x3" %>
        </div>
    </div>

    <%= form.text_field :user_id, type:"hidden", value: current_user.id%>
    <%= form.text_field :group_id, type:"hidden", value: @group.id%>

    <div class="row">
        <div class="col mb-2">
            <% form.label :houres, style: "display: block" %> Number of houres required: <br>
            <%= form.number_field :houres %>
        </div>
    <div class="col mb-2">
        <% form.label :type_of_houre, style: "display: block" %> Type of houres: <br>
        <%= form.select :type_of_presence, ["Included in group hours","To be added"] %>
    </div>

    </div>

    <script type="text/javascript"> 
        function hide(value){
            alert(value);
        }
    </script>

    <div class="row">

        <div class="col mb-2">
            <% form.label :type_of_presence, style: "display: block" %> Modality: <br>
            <%= form.select :type_of_presence, ["Presence", "Online"] , id:"modality", onclick:"hide(this)" %>
        </div>
        <div class="col mb-2">
            <% form.label :address, style: "display: block" %> Address: <br>
            <%= form.text_field :address , id:"address"%>
        </div>
    </div>

    <div class="row">
        <div class="col mb-2">
            <% form.label :city, style: "display: block" %> City: <br>
            <%= form.text_field :city %>
        </div>
        <div class="col mb-2">
            <% form.label :country, style: "display: block" %> Country: <br>
            <%= form.text_field :country %>
        </div>
    </div>
    <div class=" mt-4">
        <%= form.submit "Create", class:"btn btn-primary btn-sm" %>
    </div>



<%end%>

organizeforus/app/views/events/_position_fields.html.erb
<div class="row mt-2">
    <div class="row">
      <%= f.label :street, "Address" %><br />
      <%= f.text_field :street , class: 'form-control' %><br />
    </div>
    <div class="row">
      <%= f.label :city, "City" %><br />
      <%= f.text_field :city , class: 'form-control' %><br />
    </div>
    <div class="row">
      <%= f.label :province, "Province" %><br />
      <%= f.text_field :province , class: 'form-control' %><br />
    </div>
    <div class="row">
    <%= f.label :country, "country" %><br />
    <%= f.text_field :country , class: 'form-control' %><br />
    </div>
</div>

organizeforus/app/views/events/event_calendar.html.erb
<%if !user_signed_in? %>
  <% controller.redirect_to new_user_session_path %>
<%end%>

<div class="row mb-5 mt-5">
  <div class="col-lg-9 mx-lg-auto">
    <%= link_to 'List View', events_path, class:'btn btn-primary btn-lg mb-5' %>
    <%= link_to 'New Event', new_event_path, class:'btn btn-primary btn-lg mb-5' %>
    <div id="calendar"></div>
  </div>
</div>

organizeforus/app/views/events/show.html.erb
<html>
<head>
  <%if !user_signed_in? %>
    <% controller.redirect_to new_user_session_path %>
  <%end%>
</head>

<div class="container">
<div class="row" style="width:100% ;text-align:right">
      <div class="col" style="width:80%"> 
      </div>    
      <div class="col" > <div class="row" style=" text-align:right">
        <div class="col">
          <a href="<%= group_events_path(@group) %>" style="color: black">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-90deg-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1.146 4.854a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 4H12.5A2.5 2.5 0 0 1 15 6.5v8a.5.5 0 0 1-1 0v-8A1.5 1.5 0 0 0 12.5 5H2.707l3.147 3.146a.5.5 0 1 1-.708.708l-4-4z"/>
            </svg>
          </a>
        </div>
        <!--div class="col">
          <a href="<%= edit_group_path(@group) %>" style="color: black" id="EditGroup">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
          </svg>
          </a>
        </div-->
        <div class="col">
          <button type="button" class="btn btn-sm" id="ButtonWorkDelete" onclick="show('box')"> 
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
              <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
            </svg>
          </button>
          <div class="alert alert-danger" role="alert" id="box" style="display:none" >Are you sure?
            <%= button_to 'Delete event', group_event_path(@group,@event), method: :delete, id: "DestroyEventWork" %>
          </div>
        </div>

        <!--
        <div class="col">
          
          <a href="<%= new_group_event_path(@group) %>" style="color: black">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-plus" viewBox="0 0 16 16">
            <path d="M8 7a.5.5 0 0 1 .5.5V9H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V10H6a.5.5 0 0 1 0-1h1.5V7.5A.5.5 0 0 1 8 7z"/>
            <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
            </svg>
          </a>
        </div>
        -->
        
          </div>
      </div>
    </div> 
    
  <div class="row mt-5">
    <div class="col-md-7">
      <h1 class="display-6">Event Details</h1>
      <div class="card mb-4">
        <div class="card-body">
          <p>
            <strong class="lead">Title:</strong>
            <%= @event.title %>
          </p>
          <p>
            <strong class="lead">Description:</strong>
            <%= @event.description %>
          </p>
          <hr>
          <p>
            <strong class="lead">Start date:</strong>
            <%= @event.start_date.to_s.remove("UTC") %>
          </p>
          <p>
            <strong class="lead">End date:</strong>
            <%= @event.end_date.to_s.remove("UTC")%>
            <!--%= formatted_datetime(@event.end_date) %-->
          </p>
          <!--
          <%= link_to 'Edit', edit_event_path(@event), class: 'btn btn-primary' %> 
          <%= link_to 'Back', events_path, class: 'btn btn-primary' %>
          -->
        </div>
      </div>

      <h1 class="display-6">Event Participants</h1>
      <ul class="list-group">
        <% @event.email_guest_list.each do |guest| %>
          <li class="list-group-item">
            <div class="media">
              <!--%= image_tag 'dummy-user.png', class: 'mr-3 guest-icon' %-->
              <div class="media-body">
                <h5 class="mt-0"><%= guest %></h5>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-5">
      <% if @event.position!=nil %> <!-- se c'è una posizione la mostro -->
          <h1 class="display-6">Position</h1>

          <ul> 
            <div class="map-container">
              <div id="breweries" data-latitude=<%= @location.latitude %> data-longitude=<%= @location.longitude %> >
                  <p><%= @location.address %></p>
              </div>
              <div id="map"> </div>
            </div>

            <style type="text/css">
            #map {
              height: 300px;
              width: 100%;
            }
          </style>
                <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>


              <script type="text/javascript">
              function initMap() {
              const coords = document.getElementById("breweries");
              const city = {
                lat: parseFloat(coords.getAttribute("data-latitude")),
                lng: parseFloat(coords.getAttribute("data-longitude"))
              };
              const map = new google.maps.Map(document.getElementById("map"), {
                zoom: 10,
                center: city
              });
              const marker = new google.maps.Marker({
                position: city,
                map: map,
              });

              }
                                
              window.initMap = initMap;

            </script>
            <script async src="https://maps.googleapis.com/maps/api/js?key=<%=Rails.application.credentials.dig(:google, :google_api_key_maps)%>&callback=initMap" defer> </script>


        
          </ul>
      <% elsif !@event.meet_uri.nil? %>

      <h1 class="display-6">Event Meet</h1>
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <a href= <%= @event.meet_uri %> >  
                <svg xmlns="http://www.w3.org/2000/svg" width="1.22em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 256 211"><path fill="#00832D" d="m144.822 105.322l24.957 28.527l33.562 21.445l5.838-49.792l-5.838-48.669l-34.205 18.839z"/><path fill="#0066DA" d="M0 150.66v42.43c0 9.688 7.864 17.554 17.554 17.554h42.43l8.786-32.059l-8.786-27.925l-29.11-8.786L.001 150.66Z"/><path fill="#E94235" d="M59.984 0L0 59.984l30.876 8.765l29.108-8.765l8.626-27.545z"/><path fill="#2684FC" d="M.001 150.679h59.983V59.983H.001z"/><path fill="#00AC47" d="M241.659 25.398L203.34 56.834v98.46l38.477 31.558c5.76 4.512 14.186.4 14.186-6.922V32.18c0-7.403-8.627-11.495-14.345-6.781"/><path fill="#00AC47" d="M144.822 105.322v45.338H59.984v59.984h125.804c9.69 0 17.553-7.866 17.553-17.554v-37.796l-58.519-49.972Z"/><path fill="#FFBA00" d="M185.788 0H59.984v59.984h84.838v45.338l58.52-48.49V17.555c0-9.69-7.864-17.554-17.554-17.554"/>   
                </svg>
                  Go to meet
              </a>
            </div>
          </div>
        </div>      
      <%end%>
    </div>
  </div>
</div>


<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script type="text/javascript">
      function show(variabile) {
       if(document.getElementById(variabile).style.display=='') { 
        document.getElementById(variabile).style.display='none'; 
      }else{ 
        document.getElementById(variabile).style.display=''; 
      } 
      };
  </script>
  <script type="text/javascript">
      $(document).on('click', function (e) {
        if ($(e.target).closest("#box").length === 0 && $(e.target).closest("#ButtonWorkDelete").length === 0 ) {
          $("#box").hide();
        }
      });
  </script>


</html>

organizeforus/app/views/events/show.js.erb
$('#showGuestDetails').html("<%= escape_javascript render('show', event: @event )%>")