organizeforus/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  #Definita la route di sign_out:
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy' 
    post '/user/after_social_connection' => 'users/after_auth#create'
    get '/user/:id/:provider/unlink_account' => "users/after_auth#unlink_account", as: "unlink_account"
  end

  get '/profile' => "users#profile"


  resources :events
  resources :groups
  resources :positions

  #get 'home/index'
  root 'home#index'
  get 'home/about'
  get 'home/bho'
 
  
  resources :groups do
    resources :members , only: [:new,:edit,:create]
  end 

 resources :partecipations , only:[:new,:create,:destroy]

  resources :groups do
    resources :roles, only: [:create]
  end 
  resources :groups do
    resources :posts
  end 

  resources :posts do
    resources :comments
  end 

  resources :groups do
    resources :events
  end 

  put 'groups/:id/partecipations/edit_driver', to: 'partecipations#edit_driver', as: 'edit_driver'
  get '/groups/:group_id/partecipations', to: 'partecipations#new', as: 'new_partecipations'
  post '/groups/:group_id/partecipations', to: 'partecipations#create', as: 'partecipation_create'

  get '/groups/:id/set_created', to: 'groups#set_created', as: 'set_created'

  get '/groups/:group_id/partecipations/:role/delete_role', to: 'partecipations#delete_role', as: 'delete_role'

  get '/groups/:group_id/partecipations/show', to: 'partecipations#show', as: 'show_p'
  put '/groups/:group_id/partecipations/:member_id/update_role', to: 'partecipations#update_role', as: 'update_role'

  get '/groups/:group_id/partecipations/:member_id/update', to: 'partecipations#update', as: 'update'

  get '/groups/:group_id/partecipations/:member_id/invite', to: 'partecipations#invite', as: 'invite'


  get 'partecipations/:id/accept', to: 'partecipations#accept', as: 'accept'
  get 'partecipations/:id/decline', to: 'partecipations#decline', as: 'decline'


  get 'partecipations/:id/destroy', to: 'partecipations#destroy', as: 'destroy_partecipation'
  get 'partecipations/new_role', to: 'partecipations#new_role', as: 'new_role'
  #get '/auth/:provider/callback' => 'sessions#omniauth'

  get '/groups/:group_id/surveys/user_id/new', to: 'surveys#new', as: 'new_survey'
  post '/groups/:group_id/surveys/create', to: 'surveys#create', as: 'new_surveys'
  get '/groups/:group_id/surveys/index', to: 'surveys#index', as: 'index_survey'
  get '/groups/:group_id/surveys/:id/destroy', to: 'surveys#destroy', as: 'destroy_survey'

  get '/groups/:group_id/surveys/:survey_id/:user_id/invite', to: 'surveys#invite', as: 'invite_survey'
  post '/groups/:group_id/surveys/:survey_id/:user_id/accept', to: 'surveys#answer', as: 'answer_survey'

  get '/groups/:group_id/surveys/:survey_id/show', to: 'surveys#show', as: 'show_survey'


  get '/groups/:group_id/posts/:id/destroy' , to: 'posts#destroy', as: 'destroy_post'                                                


  put '/groups/:group_id/posts/:id/update' , to: 'posts#update', as: 'update_post'       

  post 'groups/:id/set_organization', to: 'groups#set_organization', as: 'set_organization'
                        
  get 'groups/:id/show_organization', to: 'groups#show_organization', as: 'show_organization'
  
  get 'groups/:id/:user_id/set_github_repo', to: 'groups#set_github_repo', as: 'set_github_repo'

  get 'groups/:group_id/events/:month/:day/:data_inizio/:data_fine/parameterize_date', to: 'events#parameterize_date', as: 'parameterize_date'

  

  get 'groups/:id/get_github_link', to: 'groups#get_github_link', as: 'get_github_link'

  post 'groups/:id/set_name_for_new_repository', to: 'groups#set_name_for_new_repository', as: 'set_name_for_new_repository'

  get 'groups/:id/name_repository', to: 'groups#name_repository', as: 'name_repository'

  get 'home/sign_in', to: 'home#sign_in', as: 'sign_in'

  get 'home/prova_git', to: 'home#prova_git', as: 'prova_git'

  get '/home/bho'
  get 'calendar' => 'events#event_calendar'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  match "/500", to: "errors#internal_server_error", via: :all
  match "/404", to: "errors#not_found", via: :all

  
end

organizeforus/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [ :show, :edit ,:update ,:destroy ]
  before_action :authenticate_user!
  before_action :check_id, except: [:index, :new, :create]
  before_action :correct_user, only: [:edit, :update, :set_organization]
  before_action :only_real_admin, only:[:destroy,:set_github_repo, :name_repository]
  before_action :not_already_created, only: [:name_repository]
  before_action :delete_incomplete, only: [:index]
  before_action :surveys_terminated, only: [:show]
  before_action :member_or_admin, only: [:show]

  before_action :user_google, only: [:set_organization]

include Search
  
  def check_id
    if params[:id].nil?
      redirect_to root_path, notice: "Something goes wrong"
    end
  end


  #se l'user non è autenticato non può fare nulla se non le cose specificate nella index e nella show

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end


  # GET /groups/1 or /groups/1.json
  def show
    @group=Group.find(params[:id])
    if @group.work
      render "work_group_show"
    else
      render "fun_group_show"
    end 
  end

  def show_work
  end

  def member_group
  end
  # GET /groups/new
  def new
    #authorize! :create, @group, :message => "BEWARE: you are not authorized to create new groups."
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
    @group=Group.find(params[:id])
    @partecipations=Partecipation.all
    if @group.work
      render "work_group_edit"
    else
      render "fun_group_edit"
    end 
  end


#forse da togliere
  def edit_driver
    @group=Group.find(params[:id])
    @member = @group.members.find_by(user_email: member_update_params[:driver])
    @group.members.update(:all, driver: "f")
    @member.update(driver: "t")
    respond_to do |format|
        format.html { redirect_to group_url(@group), notice: "the new designated driver is: "+ member_update_params[:driver] }  
    end
  end 


  # POST /groups or /groups.json
  def create
    #@group = Group.new(group_params)
    @group=current_user.groups.build(group_params)  
    respond_to do |format|
      if @group.work && @group.fun
        format.html { redirect_to groups_url, notice: "Impossible to create a group that is for fun end at the same time for work!" }
        format.json { render :show, location: @group, status: :unprocessable_entity }

      elsif @group.save 
        Partecipation.create(group_id: @group.id, user_id: current_user.id, accepted: true, admin: true, role: "Admin")
        format.html { redirect_to new_partecipations_url(@group)}
        format.json { render :show, status: :created, location: @group }
         
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      @group=Group.find(params[:id])
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { redirect_to edit_group_path(@group), notice: "Group was not successfully updated."}
        format.json { render :edit , status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group=Group.find(params[:id])
    if !@group.surveys.empty?
      @group.surveys.each{ |s|
        if !s.questions.empty?
          s.questions.each{|q|
            q.answers.destroy_all
          }
        end
      }
    end
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end




  def delete_role
    @group=Group.find(params[:id])
  end

  def set_created
    @group=Group.find(params[:id])
    var=@group.update(created:"t")
    if var #se il gruppo viene correttamente modificato
      #da spostare
      GroupMailer.with(group: @group, user: current_user).group_created.deliver_later
      respond_to do |format|
        format.html { redirect_to group_url(@group), notice: "Group was successfully created." }
        format.json { head :no_content }
      end
      sendNotification(@group)
      #quando il gruppo viene correttamente creato invia le notifiche di partecipazione

    else #se ci sono errori nella modifica
      @group.destroy
      respond_to do |format|
      format.html { render :edit, status: :unprocessable_entity }
      format.json { render json: @group.errors, status: :unprocessable_entity }
      end 
    end 
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def delete_incomplete
    Group.where(created: "f",user_id: current_user.id).destroy_all
  end

  def surveys_terminated
    @group=Group.find(params[:id])
    @surveys=@group.surveys
    @surveys.each { |survey|
      totale= @group.partecipations.where('created_at < ?', survey.created_at).count
      risposte=0
      survey.questions.each{ |question|
        risposte+=question.answers.count
       }

    if totale==risposte 
      if survey.score==nil
        survey.update(score: "1")
        survey.update(terminated: true)
        notify_terminated_recipent(@group,survey)
      end
    end
     }
  end


  def sendNotification(group)
    Partecipation.where(group_id: @group.id).each do |partecipation| #where.not(user_id: @group.user) per non includere l'admin
      notify_partecipation_recipent(@group, partecipation.user , partecipation.role)
    end
  end

  def user_google
    if current_user.access_token.nil?
      redirect_to root_path, notice: "You can't see slots if you are not a Google user"
    end
  end

  def set_organization
     @group = Group.find(params[:id])
     @start=@group.date_of_start
     @end_d=@group.date_of_end

     if @start.month.to_i < 10
      @ms="0"+@start.month.to_s
     else
      @ms=@start.month.to_s
     end

     if @end_d.month < 10
      @me="0"+@end_d.month.to_s
     else
      @me=@end_d.month.to_s
     end
     @try = organize_for_us(@group ,@start.year.to_s+"-"+@ms+"-"+@start.day.to_s , @end_d.year.to_s+"-"+@me+"-"+@end_d.day.to_s , @group.start_hour.strftime("%H:%M:%S") , @group.end_hour.strftime("%H:%M:%S") , (@group.min_hours_in_a_day*60 - 1))
     respond_to do |format|
      if @try==nil
          format.html { redirect_to group_url(@group),notice: "Not possible to find an organizzation" }
          format.json { render json: show, status: :unprocessable_entity }
      elsif @try==[]
        format.html { redirect_to group_url(@group),notice: "All members are free" }
        format.json { render json: show, status: :unprocessable_entity }
      else 
        format.html { redirect_to show_organization_path(@group),notice: "We have found something! Press Slots" }
        format.json { render json: show, status: :unprocessable_entity } 
      end 
    end
  end

  def stringfy_date(td)
    if td.month.to_i < 10
      ms="0"+td.month.to_s
     else
      ms=td.month.to_s
    end
     return td.year.to_s+"-"+ms+"-"+td.day.to_s 
  end
  def set_github_repo
    @group=Group.find(params[:id])
    token = current_user.gh_access_token
    if !token
      flash[:notice] = "You must have linked your Github account to your account"
      @group.update!(git_repository: nil)
      redirect_to @group and return 
    end
    url = URI.parse("https://api.github.com/user/repos")
    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true
    request = Net::HTTP::Post.new(url)
    request["Authorization"] = "token #{token}"
    request["Content-Type"] = 'application/json'
    request["Accept"] = 'application/vnd.github+json'
    name_repository=@group.git_repository
    private_or_not = (@group.status=="private")? true : false
    request.body = {name: name_repository, private: private_or_not, description: "This repository has been created by an amazing website: OrganizeForUs!!"}.to_json
    response = https.request(request)
    json = JSON.parse(response.body, symbolize_names: true)
    if eval(response.code.to_s) === 201
        url = json[:html_url]
        flash[:notice] = "Repository successfully created on your Github account!"
        @group.update!(git_url: url)
        redirect_to @group 
    elsif eval(response.code.to_s) === 422
      flash[:notice] = "#{json[:message]} Cause: #{json[:errors][0][:message]}!!"
      @group.update!(git_repository: nil)
      redirect_to name_repository_path(@group)
    else
      GroupMailer.with(user: current_user, time: Time.now).github_repo_api_error.deliver_now
      flash[:notice] = "There may be an issue with your github token... Please login again with Github... If the error persists, don't worry, or team has already been informated about your issue!!"
      @group.update!(git_repository: nil)
      redirect_to @group and return
    end
=begin
    if !@group.user.gh_username.nil? #se l'utente si è autenticato con github
      request.body = "{\n    \"name\": \"#{@group.name}\",\n    \"private\" : \"true\"\n}"
      response = https.request(request)
      resp=JSON.parse(response.read_body)
      respond_to do |format|
          if !resp.values_at("id").first.nil? #se il gruppo viene correttamente creato inserirsco link nel gruppo
            @group.update!(git_repository: "private")
              format.html { redirect_to group_url(@group),notice: "GitHub private repository created, now check the email" }
              format.json { render json: show, status: :unprocessable_entity }
              #invio invito
            if @group.user.gh_username!="organizeforus"
              url2 = URI("https://api.github.com/repos/organizeforus/#{@group.name}/transfer")
              https2 = Net::HTTP.new(url2.host, url2.port)
              https2.use_ssl = true
              request2 = Net::HTTP::Post.new(url2)

organizeforus/app/helpers/groups_helper.rb
module GroupsHelper
end

organizeforus/app/views/groups/_group.html.erb
<%if !user_signed_in? %>
  <% controller.redirect_to new_user_session_path %>
<%end%>

<div id="<%= dom_id group %>">
  <p>
    <strong>Name:</strong>
    <%= group.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= group.description %>
  </p>

</div>

organizeforus/app/views/groups/organizzation.html.erb
<%if !user_signed_in? %>
  <% controller.redirect_to new_user_session_path %>
<%end%>

<h1 class="display-6">Organize your group</h1>

organizeforus/app/views/groups/work_group_show.html.erb
<html>
<head>
  <%if !user_signed_in? %>
    <% controller.redirect_to new_user_session_path %>
  <%end%>
</head>
<body> 
<%= stylesheet_link_tag "application" %> 


  <!-- barra comandi-->
   <div class="row" style="width:100% ;text-align:right">
      <div class="col" style="width:80%"> 
      <h1 class="display-6" style="text-align:left"> <%= image_tag group_image(@group, 5000), :size => "60x60", class: "rounded-circle" %><%= @group.name %></h1>
      </div>    
      <div class="col" > 
      <div class="row" style=" text-align:right">
        <div class="col">
          <a href="<%= groups_path %>" style="color: black">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-90deg-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1.146 4.854a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 4H12.5A2.5 2.5 0 0 1 15 6.5v8a.5.5 0 0 1-1 0v-8A1.5 1.5 0 0 0 12.5 5H2.707l3.147 3.146a.5.5 0 1 1-.708.708l-4-4z"/>
            </svg>
          </a>
        </div>
        
        <div class="col">
          <a href="<%= edit_group_path(@group) %>" title="Edit" style="color: black" id="EditGroup">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
          </svg>
          </a>
        </div>
        <!--
        <div class="col">
          <a href="<%= new_group_event_path(@group) %>" title="New event" style="color: black">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-plus" viewBox="0 0 16 16">
            <path d="M8 7a.5.5 0 0 1 .5.5V9H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V10H6a.5.5 0 0 1 0-1h1.5V7.5A.5.5 0 0 1 8 7z"/>
            <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
            </svg>
          </a>
        </div>
        -->

        
        <div class="col">
          <button type="button" class="btn btn-sm" id="ButtonGroupDelete" title="Delete" onclick="show('box')"> 
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
              <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
            </svg>
          </button>
          <div class="alert alert-danger" role="alert" id="box" style="display:none" >Are you sure?
            <%= button_to 'Delete group', @group, class:"btn btn-danger btn-sm", method: :delete, id: "DestroyGroupWork" %>
          </div>
        </div>
        
      </div>
      </div>
    </div> 

    <div style="text-align: right">
    </div>
    <br>

 

  <div class="container" id="info_fun">
      <div class="row">
          <div class="col mb-2",  style="width:80%, margin-left:10px">
          <br>
          <h4 class="display-6"><%= @group.description %></h4>
            <h6 class="lead">Work group</h6>
          </div>

       

          <div class="col">     
          </div>
        </div>
    </div>

    

  </br>

  <!-- INIZIO ACCORDION -->
  <div class="container" style="width:100%" >

  <div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        Members
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <%  i=0 %>
              <% if i<3 %>
                  <% @group.partecipations.each do |member| %>
                    <div class="row"> 
                      <% if @group.accepted?(member.user.id) %> 
                        <div class="col">
                          <li  style="list-style-type: circle ; color: <%=member.role_color%>" >  
                            <span > <%= member.user.email %> </span> 
                          </li> 
                        </div>
                        <% i=i+1%>
                      <% end %>
                    </div>
                  <%end%>
              <% end %>
        <span><%= link_to "Show More",show_p_url(@group), class:"btn btn btn-sm" %></span>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Events
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      <div class="accordion-body">
      <% if !@group.events.empty? %>
        <% @group.events.each do |event|%>
          <li style='list-style-type: circle'><%= event.title%> </li>
        <%end %>
      <%else%>
        <p class="lead">No events yet</p>
      <%end%>
      <span><%= link_to "Show More", group_events_path(@group), class:"btn btn btn-sm" %></span>
      </div>  
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        Surveys
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
      <div class="accordion-body">
      <% if !@group.surveys.empty? %>
                <% i = 0 %> 
                  <% @group.surveys.active.take(3).each do |s| %>
                    <% if i < 3 && i <= @group.surveys.count %>
                      <%i=i+1%>
                      <li style='list-style-type: circle'><%= link_to s.title , show_survey_path(@group,s) %></li>
                    <%end%>
                  <%end%>
              <%else%>
              <p class="lead">No surveys yet</p>
              <%end%>
              <br>
      <span><%= link_to "Show More", index_survey_url(@group), class:"btn btn btn-sm" %></span>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingFour">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
        Posts
      </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <span><%= link_to "Show more", group_posts_url(@group), id:"Posts",  class:"btn btn btn-sm" %></span>
      </div>
    </div>
  </div>

<div class="accordion-item">
    <h2 class="accordion-header" id="headingFive">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
        Group's hours stats
      </button>
    </h2>
    <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive" data-bs-parent="#accordionExample">
      <div class="accordion-body">
<div class="row", style="align: center">
  <div class="col", style="align: left", id="grafico1">
   <%worked_hours=0%>
      <%extra_hours=0%>
      <%added_hours=0%>
      <% @group.events.each do |event| %>
        <%if event.type_of_hours=="To take from to Group's hours"%>
        <%worked_hours=worked_hours+(event.end_date-event.start_date)/3600%>
          <%if worked_hours>@group.hours%>
          <%rimanenza=worked_hours-@group.hours%>
           <%worked_hours=worked_hours-rimanenza%>
           <%extra_hours=extra_hours+rimanenza%>
          <%end%>
        <%elsif event.type_of_hours=="To add from Group's hours" %>
          <%added_hours=added_hours+(event.end_date-event.start_date)/3600%>
        <%end%>   
      <%end%>  
      </div>
      <%if added_hours==0 && extra_hours==0%>
         <div class="col", style="align: right; visibility: hidden", id="grafico2">
         </div>
      <%else%>
         <div class="col", style="align: right", id="grafico2">
         </div>
      <%end%>
    </div>
      </div>
    </div>
  </div>
</div>
  
</div>
  <!-- FINE ACCORDION -->
<br>
  <script src="https://cdn.anychart.com/releases/8.11.0/js/anychart-core.min.js"></script>
  <script src="https://cdn.anychart.com/releases/8.11.0/js/anychart-pie.min.js"></script>
  <script src="https://cdn.anychart.com/releases/8.11.0/js/anychart-exports.min.js"></script>
<script type="text/javascript">
anychart.onDocumentReady(function () {

    // create data
    var data = [

      {x: "Remaining hours", value: <%=@group.hours-worked_hours%>},
      {x: "Worked hours", value: <%=worked_hours%>},
    ];

    // create a chart and set the data
    var chart = anychart.pie();
    chart.data(data);
    // set the chart title
    chart.title("Group's scheduled hours stats");

    // set the container id
    chart.container("grafico1");

    // initiate drawing the chart
    chart.draw();
});

anychart.onDocumentReady(function () {

    // create data
    var data = [

      {x: "Added hours", value: <%=added_hours%>},
      {x: "Extra hours", value: <%=extra_hours%>},
    ];

    // create a chart and set the data
    var chart = anychart.pie();
    chart.data(data);
    // set the chart title
    chart.title("Group's extra hours stats");

    // set the container id
    chart.container("grafico2");

    // initiate drawing the chart
    chart.draw();
});

     </script>   
  <br>
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script type="text/javascript">
      function show(variabile) {
       if(document.getElementById(variabile).style.display=='') { 
        document.getElementById(variabile).style.display='none'; 
      }else{ 
        document.getElementById(variabile).style.display=''; 
      } 
      };
  </script>
  <script type="text/javascript">
      $(document).on('click', function (e) {
        if ($(e.target).closest("#box").length === 0 && $(e.target).closest("#ButtonGroupDelete").length === 0 ) {
          $("#box").hide();
        }
      });
  </script>

<!-- Index eventi 
<%= link_to "Events", group_events_path(@group) %>
-->
<div>

  <% if @group.git_repository.nil? || @group.git_repository== "422"%>
    <span><%= link_to "Create a github repository for the group", name_repository_path(@group), class:"btn btn btn-sm" %></span>
  <%else%>
    <%=link_to "Click to see OrganizeForUs's GitHub repositories", get_github_link_path(@group) , method: :get,class:"btn btn btn-sm"%>
    <!--a href="<%=@group.git_url%>", class:"btn btn btn-sm">Click to see OrganizeForUs's GitHub repositories</a-->
  <%end%>
</div>
  </body>
</html>
</br>
</br>